#!/bin/sh

zsh_prefetch()
{
  package define base_url "http://sourceforge.net/projects/zsh/files/zsh-dev/${package_version}"
}

zsh_postconfigure()
{
  # Enable pcre & regex to be loaded
  if [[ ${static_flag:-0} == 1 || "$LDFLAGS" =~ "static" ]]
  then
    sed -Ei "/zsh\/(pcre|regex)/ { s/link=no/link=static/ ; s/auto=yes/auto=no/ }" config.modules
  else
    sed -Ei "/zsh\/(pcre|regex)/ { s/link=no/link=dynamic/ ; s/auto=yes/auto=no/ }" config.modules
  fi
  grep -E "zsh\/(pcre|regex)" config.modules | __sm.log.debug package -
}

zsh_postinstall()
{
  if user is root
  then
    true
    # TODO: make this opt-in
    # upgrade_binary
  fi
}

upgrade_binary()
{
  original_binary="${prefix_path}/bin/${extension}"

  if [[ -x "$original_binary" ]] ; then
    original_version=$("$original_binary" -c 'printf $ZSH_VERSION')

    log "Preserving old binary as '$original_binary-$original_version'..."

    move_file "${original_binary}" to "${original_binary}-$original_version"
  fi
}

zsh_setup()
{
  local file

  for file in .zshenv .zshrc
  do
    if file_does_not_exist "${HOME}/${file}"
    then
      install_template "zsh/${file}" to "${HOME}/${file}" mode 0644
    fi
  done
}
